name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: 
          - 16.14.2-alpine3.15
          - 17.8.0-alpine3.14
          - 17.8.0-alpine3.15
          - 15.8.0-alpine3.10
          - 14.15.5-alpine3.10
          - 12.20.2-alpine3.10
          - 10.23.3-alpine3.10
          
    steps:
      - name: Test environment variables
        env:
          NODE_VERSION: ${{ matrix.node }}
        run: echo $NODE_VERSION
        
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set node version
        run: sed -i 's/\$NODE_VERSION/${{ matrix.node }}/' Dockerfile
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: eustatos/node-sass:${{ matrix.node }}
          build-args: |
            NODE_VERSION=10.23.3-alpine3.10
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
